// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybamwxsqsxaxwoivedsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliYW13eHNxc3hheHdvaXZlZHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjg3NzksImV4cCI6MjA2NjYwNDc3OX0.sJcOUTeIqRdqjzrqsvFZIwLvPD9ifI0ThnsG13RJ0qU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});